# Prefect Deployment Configuration
# Deploy this to Prefect Cloud with: prefect deploy -f deployment/prefect_deployment.yaml

name: weekly-meal-planner
version: 1.0.0
description: "Weekly meal planning agent with Claude, Slack approval, and Todoist integration"

# Flow configuration
flow_name: weekly-meal-planner
entrypoint: src/main.py:weekly_meal_planner_flow

# Work pool configuration (Prefect Cloud Managed Execution)
work_pool:
  name: managed-execution
  job_variables:
    # Python version
    python_version: "3.11"

    # Install dependencies
    pip_packages:
      - "prefect>=3.0.0"
      - "prefect-client>=3.0.0"
      - "anthropic>=0.39.0"
      - "slack-sdk>=3.33.0"
      - "logfire>=0.70.0"
      - "httpx>=0.27.0"
      - "pydantic>=2.0.0"
      - "python-dotenv>=1.0.0"

# Schedule: Every Saturday at 5pm UTC
schedules:
  - cron: "0 17 * * 6"  # 5pm UTC on Saturdays
    timezone: "UTC"
    active: true

# Parameters (can be overridden at runtime)
parameters:
  dietary_preferences: "I like quick, healthy meals under 20 minutes for 3 people including one child."

# Tags for organization
tags:
  - meal-planning
  - claude
  - slack
  - todoist
  - weekly

# Environment variables
# IMPORTANT: Set these as Prefect secrets or environment variables
# Do NOT commit sensitive values to git
#
# Required environment variables:
# - ANTHROPIC_API_KEY
# - SLACK_BOT_TOKEN
# - SLACK_CHANNEL_ID
# - TODOIST_GROCERY_PROJECT_ID
# - TODOIST_MCP_SERVER_URL
# - PREFECT_API_KEY
# - PREFECT_API_URL
# - LOGFIRE_TOKEN
#
# Optional:
# - TODOIST_MCP_AUTH_TOKEN
# - SLACK_SIGNING_SECRET
# - APPROVAL_TIMEOUT_SECONDS (default: 86400)
# - SLACK_POLL_INTERVAL_SECONDS (default: 30)
# - MAX_REGENERATION_ATTEMPTS (default: 3)

# Pull step (optional - for git-based deployments)
# pull:
#   - prefect.deployments.steps.git_clone:
#       repository: "https://github.com/your-org/meal-planner-agent.git"
#       branch: "main"

# Build step (optional - for custom Docker images)
# build: null

# Push step (optional - for pushing to registries)
# push: null

# Enforce parameter schema
enforce_parameter_schema: true

# Flow run settings
flow_run:
  # Timeout for the entire flow (25 hours to account for 24hr approval timeout)
  timeout_seconds: 90000

  # Retry policy
  retries: 0  # Don't retry the entire flow, let tasks handle retries

  # Log prints
  log_prints: true
